# syntax=docker/dockerfile:1

# ---- Base ----
# Pin a specific Node LTS on Alpine for small, reproducible images.
FROM node:20-alpine AS base
# libc6-compat is recommended by Next.js for certain native deps on Alpine.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# ---- Dependencies ----
# Installed in a dedicated layer so they are cached unless the lockfile changes.
FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

# ---- Builder ----
# Builds the Next.js app and emits the standalone server output.
FROM base AS builder
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# ---- Runner ----
# Minimal production image: only the standalone server + static assets.
FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Port the server listens on. Override at build time (--build-arg PORT=...)
# or at runtime (-e PORT=...).
ARG PORT=3000
ENV PORT=${PORT}
ENV HOSTNAME=0.0.0.0

# Run as an unprivileged user for security.
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

# The standalone output already bundles a trimmed node_modules and server.js.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE ${PORT}

# server.js is generated by Next.js `output: 'standalone'` and honors $PORT.
CMD ["node", "server.js"]
